In [51]:
'''
Used Car Price Prediction Dataset is a comprehensive collection of automotive information extracted from the popular automotive marketplace website, https://www.cars.com. This dataset comprises 4,009 data points, each representing a unique vehicle listing, and includes nine distinct features providing valuable insights into the world of automobiles.
'''

'\nUsed Car Price Prediction Dataset is a comprehensive collection of automotive information extracted from the popular automotive marketplace website, https://www.cars.com. This dataset comprises 4,009 data points, each representing a unique vehicle listing, and includes nine distinct features providing valuable insights into the world of automobiles.\n'

In [52]:
import pandas as pd
import numpy as np

In [53]:
df=pd.read_csv('used_cars.csv')

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   object
 1   model         4009 non-null   object
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   object
 4   fuel_type     3839 non-null   object
 5   engine        4009 non-null   object
 6   transmission  4009 non-null   object
 7   ext_col       4009 non-null   object
 8   int_col       4009 non-null   object
 9   accident      3896 non-null   object
 10  clean_title   3413 non-null   object
 11  price         4009 non-null   object
dtypes: int64(1), object(11)
memory usage: 376.0+ KB

In [55]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

# Cleaning data
1. handling missing values
2. check duplicate data 
3. check data types 
4. understand the dataset

In [56]:
# Check for null values
df.isnull().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [57]:
# check for missing values
features_with_na= [feature for feature in df.columns if df[feature].isnull().sum() >=1 ]
features_with_na

['fuel_type', 'accident', 'clean_title']

In [58]:
# percentage of missing values
for feature in features_with_na:
    print(feature , np.round(df[feature].isnull().mean()*100,2), '% missing values')

fuel_type 4.24 % missing values
accident 2.82 % missing values
clean_title 14.87 % missing values

In [59]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [60]:
df['fuel_type'].value_counts()

fuel_type
Gasoline          3309
Hybrid             194
E85 Flex Fuel      139
Diesel             116
–                   45
Plug-In Hybrid      34
not supported        2
Name: count, dtype: int64

In [61]:
df['fuel_type'] = df['fuel_type'].replace('not supported', '–')

In [62]:
df['fuel_type'].value_counts()

fuel_type
Gasoline          3309
Hybrid             194
E85 Flex Fuel      139
Diesel             116
–                   47
Plug-In Hybrid      34
Name: count, dtype: int64

In [63]:
df['fuel_type'].fillna('Gasoline', inplace=True)

C:\Users\sawan\AppData\Local\Temp\ipykernel_12952\1120006450.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fuel_type'].fillna('Gasoline', inplace=True)

In [64]:
df['accident'].value_counts()

accident
None reported                             2910
At least 1 accident or damage reported     986
Name: count, dtype: int64

In [65]:
df['accident'].fillna('None reported', inplace=True)

C:\Users\sawan\AppData\Local\Temp\ipykernel_12952\999459061.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['accident'].fillna('None reported', inplace=True)

In [66]:
''' 
Clean Title: Evaluate the availability of a clean title, which can impact the vehicle's resale value and legal status.
'''
df['clean_title'].value_counts()

clean_title
Yes    3413
Name: count, dtype: int64

In [67]:
df['clean_title'].fillna('No', inplace=True)

C:\Users\sawan\AppData\Local\Temp\ipykernel_12952\246093981.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['clean_title'].fillna('No', inplace=True)

In [68]:
df.isnull().sum()

brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [69]:
df.dtypes

brand           object
model           object
model_year       int64
milage          object
fuel_type       object
engine          object
transmission    object
ext_col         object
int_col         object
accident        object
clean_title     object
price           object
dtype: object

In [70]:
df['milage'] = df['milage'].astype(str)  # convert to string
df['milage'] = df['milage'].str.replace('mi.', '', regex=False)  # remove 'mi.'
df['milage'] = df['milage'].str.replace(',', '')  # remove commas
df['milage'] = df['milage'].str.strip()  # remove any leading/trailing whitespace
df['milage'] = df['milage'].astype(int)  # convert to integer

In [71]:
df['milage']

0       51000
1       34742
2       22372
3       88900
4        9835
        ...
4004      714
4005    10900
4006     2116
4007    33000
4008    43000
Name: milage, Length: 4009, dtype: int64

In [72]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,34742,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,22372,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,No,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,88900,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,9835,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,No,"$34,999"

In [73]:
df.dtypes

brand           object
model           object
model_year       int64
milage           int64
fuel_type       object
engine          object
transmission    object
ext_col         object
int_col         object
accident        object
clean_title     object
price           object
dtype: object

In [74]:
df['engine'].unique()

array(['300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability',
       '3.8L V6 24V GDI DOHC', '3.5 Liter DOHC', ...,
       '136.0HP 1.8L 4 Cylinder Engine Gasoline Fuel',
       '270.0HP 2.0L 4 Cylinder Engine Gasoline Fuel',
       '420.0HP 5.9L 12 Cylinder Engine Gasoline Fuel'],
      shape=(1146,), dtype=object)

In [75]:
df.drop('engine', axis=1 , inplace=True)

In [76]:
df['transmission'].value_counts()

transmission
A/T                                  1037
8-Speed A/T                           406
Transmission w/Dual Shift Mode        398
6-Speed A/T                           362
6-Speed M/T                           248
                                     ...
10-Speed Automatic with Overdrive       1
9-Speed Automatic with Auto-Shift       1
SCHEDULED FOR OR IN PRODUCTION          1
6 Speed Mt                              1
8-Speed Manual                          1
Name: count, Length: 62, dtype: int64

In [77]:
# changing data typeof price column
df['price'] = df['price'].astype(str)  # convert to string
df['price'] = df['price'].str.replace('$', '', regex=False)  # remove 'mi.'
df['price'] = df['price'].str.replace(',', '')  # remove commas
df['price'] = df['price'].str.strip()  # remove any leading/trailing whitespace
df['price'] = df['price'].astype(int)  # convert to integer

In [78]:
df.dtypes

brand           object
model           object
model_year       int64
milage           int64
fuel_type       object
transmission    object
ext_col         object
int_col         object
accident        object
clean_title     object
price            int64
dtype: object

In [79]:
# getting numerical features
num_features=[feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical features are ', len(num_features))

Num of Numerical features are  3

In [80]:
#categorical features
cat_features=[feature for feature in df.columns if feature not in num_features]
print('Num of categorical features are ', len(cat_features))

Num of categorical features are  8

In [81]:
# discrete features
dis_features= [feature for feature in df.columns if len(df[feature].unique()) <=25]
print('Num of discrete features are ', len(dis_features))

Num of discrete features are  3

In [82]:
x=df.drop('price', axis=1)
y=df['price']

In [83]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression

In [84]:
# Column transformer
cat_features= x.select_dtypes(include='object').columns

num_features= x.select_dtypes(exclude='object').columns
from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import ColumnTransformer
num_transformer= StandardScaler()
onehot= OneHotEncoder(drop='first', handle_unknown='ignore')

In [85]:
preprocessor=ColumnTransformer(
    [
        ('One hot' , onehot , cat_features),
        ('Standard' , num_transformer , num_features)
    ]
)

In [ ]:
# Train test split
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.3 , random_state=22)
# Better approach:
from sklearn.pipeline import Pipeline 
from sklearn.preprocessing import StandardScaler 
# Create pipeline
pipeline = Pipeline([ ('preprocessor', preprocessor), ('model', RandomForestRegressor()) ]) 
# Fit on training data only 
pipeline.fit(x_train, y_train)
y_pred = pipeline.predict(x_test)

ValueError: Cannot center sparse matrices: pass `with_mean=False` instead. See docstring for motivation and alternatives.

In [ ]:
x_train=preprocessor.fit_transform(x_train)
x_test= preprocessor.transform(x_test)

In [ ]:
pd.DataFrame(x_train).head()

In [ ]:
x_test

In [ ]:

from sklearn.metrics import mean_absolute_error ,mean_squared_error , r2_score , root_mean_squared_error

In [ ]:
models={
    'Random forest':RandomForestRegressor(),
    'Decision Tree':DecisionTreeRegressor(),
    'Logistic regression':LogisticRegression()
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train , y_train)
    
    y_train_pred= model.predict(x_train)
    y_test_pred= model.predict(x_test)
    
    #training set performance
    model_train_rsme=root_mean_squared_error(y_train , y_train_pred)
    model_train_mae= mean_absolute_error(y_train , y_train_pred )
    model_train_mse= mean_squared_error(y_train , y_train_pred)
    model_train_r2score= r2_score(y_train , y_train_pred)
    
    #test set performance
    model_test_rsme=root_mean_squared_error(y_test , y_test_pred)
    model_test_mae= mean_absolute_error(y_test , y_test_pred )
    model_test_mse= mean_squared_error(y_test , y_test_pred)
    model_test_r2score= r2_score(y_test , y_test_pred)
    
    print(list(models.keys())[i])
    
    print('Model performance for training set')
    print('- Mean squared error :{:.4f}'.format(model_train_mse))
    print('- Mean absolute error: {:.4f}'.format(model_train_mae))
    print('- Root mean squared error : {:.4f}'.format(model_train_rsme))
    print('- R2_score : {:.4f}'.format(model_train_r2score))
    
    print('='*35)
    
    print('Model performance for test set')
    print('- Mean squared error :{:.4f}'.format(model_train_mse))
    print('- Mean absolute error: {:.4f}'.format(model_train_mae))
    print('- Root mean squared error : {:.4f}'.format(model_train_rsme))
    print('- R2_score : {:.4f}'.format(model_train_r2score))
    
    print('='*35)
    print()

In [ ]:
# Hyperparameter tuning 

from sklearn.model_selection import GridSearchCV
rf=RandomForestRegressor(random_state=22)
rf_param = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2']
}

gdr= GridSearchCV(estimator=rf , param_grid=rf_param , cv=5 , n_jobs=-1 , verbose=2, scoring='r2')

In [ ]:
gdr.fit(x_train , y_train)

In [ ]:
# Best paramters 
print('Best parameters :', gdr.best_params_)
print('Best r2 score from cv :' , gdr.best_score_)

In [ ]:
#Evaluate on test set
best_model= gdr.best_estimator_
y_pred= best_model.predict(x_test)

In [ ]:
print("Test R2 score:", r2_score(y_test, y_pred))
print("Test MAE:", mean_absolute_error(y_test, y_pred))
print("Test RMSE:", root_mean_squared_error(y_test, y_pred))

In [ ]:
df.head()

,brand,model,model_year,milage,fuel_type,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000,E85 Flex Fuel,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300
1,Hyundai,Palisade SEL,2021,34742,Gasoline,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005
2,Lexus,RX 350 RX 350,2022,22372,Gasoline,Automatic,Blue,Black,None reported,No,54598
3,INFINITI,Q50 Hybrid Sport,2015,88900,Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500
4,Audi,Q3 45 S line Premium Plus,2021,9835,Gasoline,8-Speed Automatic,Glacier White Metallic,Black,None reported,No,34999

In [ ]:
# # Better approach:
# from sklearn.pipeline import Pipeline 
# # Create pipeline
# pipeline = Pipeline([ ('preprocessor', preprocessor), ('scaler', StandardScaler()), ('model', RandomForestRegressor()) ]) 
# # Fit on training data only 
# pipeline.fit(x_train, y_train)
# # y_pred = pipeline.predict(x_test)