In [2]:
'''
Used Car Price Prediction Dataset is a comprehensive collection of automotive information extracted from the popular automotive marketplace website, https://www.cars.com. This dataset comprises 4,009 data points, each representing a unique vehicle listing, and includes nine distinct features providing valuable insights into the world of automobiles.
'''

'\nUsed Car Price Prediction Dataset is a comprehensive collection of automotive information extracted from the popular automotive marketplace website, https://www.cars.com. This dataset comprises 4,009 data points, each representing a unique vehicle listing, and includes nine distinct features providing valuable insights into the world of automobiles.\n'

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('used_cars.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   object
 1   model         4009 non-null   object
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   object
 4   fuel_type     3839 non-null   object
 5   engine        4009 non-null   object
 6   transmission  4009 non-null   object
 7   ext_col       4009 non-null   object
 8   int_col       4009 non-null   object
 9   accident      3896 non-null   object
 10  clean_title   3413 non-null   object
 11  price         4009 non-null   object
dtypes: int64(1), object(11)
memory usage: 376.0+ KB

In [6]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

# Cleaning data
1. handling missing values
2. check duplicate data 
3. check data types 
4. understand the dataset

In [7]:
# Check for null values
df.isnull().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [8]:
# check for missing values
features_with_na= [feature for feature in df.columns if df[feature].isnull().sum() >=1 ]
features_with_na

['fuel_type', 'accident', 'clean_title']

In [9]:
# percentage of missing values
for feature in features_with_na:
    print(feature , np.round(df[feature].isnull().mean()*100,2), '% missing values')

fuel_type 4.24 % missing values
accident 2.82 % missing values
clean_title 14.87 % missing values

In [10]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [11]:
df['fuel_type'].value_counts()

fuel_type
Gasoline          3309
Hybrid             194
E85 Flex Fuel      139
Diesel             116
–                   45
Plug-In Hybrid      34
not supported        2
Name: count, dtype: int64

In [12]:
df['fuel_type'] = df['fuel_type'].replace('not supported', '–')

In [13]:
df['fuel_type'].value_counts()

fuel_type
Gasoline          3309
Hybrid             194
E85 Flex Fuel      139
Diesel             116
–                   47
Plug-In Hybrid      34
Name: count, dtype: int64

In [14]:
df['fuel_type'].fillna('Gasoline', inplace=True)

C:\Users\sawan\AppData\Local\Temp\ipykernel_3352\1120006450.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fuel_type'].fillna('Gasoline', inplace=True)

In [15]:
df['accident'].value_counts()

accident
None reported                             2910
At least 1 accident or damage reported     986
Name: count, dtype: int64

In [16]:
df['accident'].fillna('None reported', inplace=True)

C:\Users\sawan\AppData\Local\Temp\ipykernel_3352\999459061.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['accident'].fillna('None reported', inplace=True)

In [17]:
''' 
Clean Title: Evaluate the availability of a clean title, which can impact the vehicle's resale value and legal status.
'''
df['clean_title'].value_counts()

clean_title
Yes    3413
Name: count, dtype: int64

In [18]:
df['clean_title'].fillna('No', inplace=True)

C:\Users\sawan\AppData\Local\Temp\ipykernel_3352\246093981.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['clean_title'].fillna('No', inplace=True)

In [19]:
df.isnull().sum()

brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [20]:
df.dtypes

brand           object
model           object
model_year       int64
milage          object
fuel_type       object
engine          object
transmission    object
ext_col         object
int_col         object
accident        object
clean_title     object
price           object
dtype: object

In [21]:
df['milage'] = df['milage'].astype(str)  # convert to string
df['milage'] = df['milage'].str.replace('mi.', '', regex=False)  # remove 'mi.'
df['milage'] = df['milage'].str.replace(',', '')  # remove commas
df['milage'] = df['milage'].str.strip()  # remove any leading/trailing whitespace
df['milage'] = df['milage'].astype(int)  # convert to integer

In [22]:
df['milage']

0       51000
1       34742
2       22372
3       88900
4        9835
        ...
4004      714
4005    10900
4006     2116
4007    33000
4008    43000
Name: milage, Length: 4009, dtype: int64

In [23]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,34742,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,22372,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,No,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,88900,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,9835,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,No,"$34,999"

In [24]:
df.dtypes

brand           object
model           object
model_year       int64
milage           int64
fuel_type       object
engine          object
transmission    object
ext_col         object
int_col         object
accident        object
clean_title     object
price           object
dtype: object

In [25]:
df['engine'].unique()

array(['300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability',
       '3.8L V6 24V GDI DOHC', '3.5 Liter DOHC', ...,
       '136.0HP 1.8L 4 Cylinder Engine Gasoline Fuel',
       '270.0HP 2.0L 4 Cylinder Engine Gasoline Fuel',
       '420.0HP 5.9L 12 Cylinder Engine Gasoline Fuel'],
      shape=(1146,), dtype=object)

In [26]:
df.drop('engine', axis=1 , inplace=True)

In [27]:
df['transmission'].value_counts()

transmission
A/T                                  1037
8-Speed A/T                           406
Transmission w/Dual Shift Mode        398
6-Speed A/T                           362
6-Speed M/T                           248
                                     ...
10-Speed Automatic with Overdrive       1
9-Speed Automatic with Auto-Shift       1
SCHEDULED FOR OR IN PRODUCTION          1
6 Speed Mt                              1
8-Speed Manual                          1
Name: count, Length: 62, dtype: int64

In [28]:
# changing data typeof price column
df['price'] = df['price'].astype(str)  # convert to string
df['price'] = df['price'].str.replace('$', '', regex=False)  # remove 'mi.'
df['price'] = df['price'].str.replace(',', '')  # remove commas
df['price'] = df['price'].str.strip()  # remove any leading/trailing whitespace
df['price'] = df['price'].astype(int)  # convert to integer

In [29]:
df.dtypes

brand           object
model           object
model_year       int64
milage           int64
fuel_type       object
transmission    object
ext_col         object
int_col         object
accident        object
clean_title     object
price            int64
dtype: object

In [30]:
# getting numerical features
num_features=[feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical features are ', len(num_features))

Num of Numerical features are  3

In [31]:
#categorical features
cat_features=[feature for feature in df.columns if feature not in num_features]
print('Num of categorical features are ', len(cat_features))

Num of categorical features are  8

In [32]:
# discrete features
dis_features= [feature for feature in df.columns if len(df[feature].unique()) <=25]
print('Num of discrete features are ', len(dis_features))

Num of discrete features are  3

In [33]:
x=df.drop('price', axis=1)
y=df['price']

In [34]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostRegressor
from xgboost import XGBRegressor

In [35]:
# Column transformer
cat_features= x.select_dtypes(include='object').columns

num_features= x.select_dtypes(exclude='object').columns
from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import ColumnTransformer
num_transformer= StandardScaler(with_mean=False)
onehot= OneHotEncoder(drop='first', handle_unknown='ignore')

In [36]:
preprocessor=ColumnTransformer(
    [
        ('One hot' , onehot , cat_features),
        ('Standard' , num_transformer , num_features)
    ]
)

In [37]:
# Train test split
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.3 , random_state=22)
# Better approach:
from sklearn.pipeline import Pipeline 
# Create pipeline
pipeline = Pipeline([ ('preprocessor', preprocessor), ('model', XGBRegressor()) ]) 
# Fit on training data only 
pipeline.fit(x_train, y_train)
y_pred = pipeline.predict(x_test)

C:\Users\sawan\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 3, 4, 5] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [38]:
x_train=preprocessor.fit_transform(x_train)
x_test= preprocessor.transform(x_test)

C:\Users\sawan\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 3, 4, 5] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [39]:
pd.DataFrame(x_train).head()

                                                   0
0  <Compressed Sparse Row sparse matrix of dtype ...
1  <Compressed Sparse Row sparse matrix of dtype ...
2  <Compressed Sparse Row sparse matrix of dtype ...
3  <Compressed Sparse Row sparse matrix of dtype ...
4  <Compressed Sparse Row sparse matrix of dtype ...

In [40]:
x_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10951 stored elements and shape (1203, 2030)>

In [41]:

from sklearn.metrics import mean_absolute_error ,mean_squared_error , r2_score , root_mean_squared_error

In [42]:
models={
    'Random forest':RandomForestRegressor(),
    'Decision Tree':DecisionTreeRegressor(),
    'Logistic regression':LogisticRegression(),
    'Ada boost regressor':AdaBoostRegressor(),
    'XGB Regressor': XGBRegressor()
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train , y_train)
    
    y_train_pred= model.predict(x_train)
    y_test_pred= model.predict(x_test)
    
    #training set performance
    model_train_rsme=root_mean_squared_error(y_train , y_train_pred)
    model_train_mae= mean_absolute_error(y_train , y_train_pred )
    model_train_mse= mean_squared_error(y_train , y_train_pred)
    model_train_r2score= r2_score(y_train , y_train_pred)
    
    #test set performance
    model_test_rsme=root_mean_squared_error(y_test , y_test_pred)
    model_test_mae= mean_absolute_error(y_test , y_test_pred )
    model_test_mse= mean_squared_error(y_test , y_test_pred)
    model_test_r2score= r2_score(y_test , y_test_pred)
    
    print(list(models.keys())[i])
    
    print('Model performance for training set')
    print('- Mean squared error :{:.4f}'.format(model_train_mse))
    print('- Mean absolute error: {:.4f}'.format(model_train_mae))
    print('- Root mean squared error : {:.4f}'.format(model_train_rsme))
    print('- R2_score : {:.4f}'.format(model_train_r2score))
    
    print('='*35)
    
    print('Model performance for test set')
    print('- Mean squared error :{:.4f}'.format(model_train_mse))
    print('- Mean absolute error: {:.4f}'.format(model_train_mae))
    print('- Root mean squared error : {:.4f}'.format(model_train_rsme))
    print('- R2_score : {:.4f}'.format(model_train_r2score))
    
    print('='*35)
    print()

Random forest
Model performance for training set
- Mean squared error :366669030.5698
- Mean absolute error: 5114.8235
- Root mean squared error : 19148.6039
- R2_score : 0.9232
===================================
Model performance for test set
- Mean squared error :366669030.5698
- Mean absolute error: 5114.8235
- Root mean squared error : 19148.6039
- R2_score : 0.9232
===================================

Decision Tree
Model performance for training set
- Mean squared error :0.0000
- Mean absolute error: 0.0000
- Root mean squared error : 0.0000
- R2_score : 1.0000
===================================
Model performance for test set
- Mean squared error :0.0000
- Mean absolute error: 0.0000
- Root mean squared error : 0.0000
- R2_score : 1.0000
===================================

C:\Users\sawan\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic regression
Model performance for training set
- Mean squared error :4591127247.9932
- Mean absolute error: 21258.5891
- Root mean squared error : 67757.8575
- R2_score : 0.0382
===================================
Model performance for test set
- Mean squared error :4591127247.9932
- Mean absolute error: 21258.5891
- Root mean squared error : 67757.8575
- R2_score : 0.0382
===================================

Ada boost regressor
Model performance for training set
- Mean squared error :1963296965.4630
- Mean absolute error: 31750.1921
- Root mean squared error : 44309.1070
- R2_score : 0.5887
===================================
Model performance for test set
- Mean squared error :1963296965.4630
- Mean absolute error: 31750.1921
- Root mean squared error : 44309.1070
- R2_score : 0.5887
===================================

XGB Regressor
Model performance for training set
- Mean squared error :119378936.0000
- Mean absolute error: 7993.3569
- Root mean squared error : 10926.0664
- R2_score : 0.9750
===================================
Model performance for test set
- Mean squared error :119378936.0000
- Mean absolute error: 7993.3569
- Root mean squared error : 10926.0664
- R2_score : 0.9750
===================================

In [43]:
# Hyperparameter tuning 

from sklearn.model_selection import GridSearchCV
rf=RandomForestRegressor(random_state=22)
ada=AdaBoostRegressor(random_state=22)
xgb=XGBRegressor(random_state=22)
rf_param = {
    'n_estimators': [50 , 70 , 90,100],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2']
}
ada_param = {
    'n_estimators': [50, 70, 90, 100],
    'learning_rate': [0.01, 0.1, 1.0],
    'loss': ['linear', 'square', 'exponential']
}
XGB_param={
    'n_estimators': [50, 70, 90, 100],
    'max_depth': [None, 10, 20],
    'learning_rate': [0.01, 0.1, 1.0],
    'colsample_bytree': [0.5, 0.7, 1.0]
}

gdr= GridSearchCV(estimator=xgb , param_grid=XGB_param , cv=5 , n_jobs=-1 , verbose=2, scoring='r2')

In [44]:
gdr.fit(x_train , y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    importance_type=None,
                                    interaction_constraints=None...
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'colsample_bytree': [0.5, 0.7, 1.0],
                         'learning_rate': [0.01, 0.1, 1.0],
                         'max_depth': [None, 10, 20],
                         'n_estimators': [50, 70, 90, 100]},
             scoring='r2', verbose=2)

In [45]:
# Best paramters 
print('Best parameters :', gdr.best_params_)
print('Best r2 score from cv :' , gdr.best_score_)

Best parameters : {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 20, 'n_estimators': 100}
Best r2 score from cv : 0.5510480165481567

In [46]:
#Evaluate on test set
best_model= gdr.best_estimator_
y_pred= best_model.predict(x_test)

In [47]:
print("Test R2 score:", r2_score(y_test, y_pred))
print("Test MAE:", mean_absolute_error(y_test, y_pred))
print("Test RMSE:", root_mean_squared_error(y_test, y_pred))

Test R2 score: 0.17575645446777344
Test MAE: 14217.0576171875
Test RMSE: 88494.4375

In [48]:
df.head()

,brand,model,model_year,milage,fuel_type,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000,E85 Flex Fuel,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300
1,Hyundai,Palisade SEL,2021,34742,Gasoline,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005
2,Lexus,RX 350 RX 350,2022,22372,Gasoline,Automatic,Blue,Black,None reported,No,54598
3,INFINITI,Q50 Hybrid Sport,2015,88900,Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500
4,Audi,Q3 45 S line Premium Plus,2021,9835,Gasoline,8-Speed Automatic,Glacier White Metallic,Black,None reported,No,34999

In [49]:
randomcv_models= [('Adaboost', ada, ada_param),
                  ('RandomForest', rf, rf_param),
                  ('XGBoost', xgb, XGB_param)
                 ]

In [50]:
from sklearn.model_selection import RandomizedSearchCV

model_param= {}
for name , model , params in randomcv_models:
    random= RandomizedSearchCV(estimator=model , 
                               param_distributions=params,
                               n_iter=100,
                               cv=3,
                               verbose=2,
                               random_state=22,
                               n_jobs=-1)
    random.fit(x_train , y_train)
    model_param[name]= random.best_params_
    
for model_name in model_param:
    print(f"--------------------Best params for {model_name}--------------------")
    print(model_param[model_name])
    print('\n')

Fitting 3 folds for each of 36 candidates, totalling 108 fits

C:\Users\sawan\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 36 is smaller than n_iter=100. Running 36 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
C:\Users\sawan\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 96 is smaller than n_iter=100. Running 96 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 3 folds for each of 96 candidates, totalling 288 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
--------------------Best params for Adaboost--------------------
{'n_estimators': 100, 'loss': 'exponential', 'learning_rate': 0.01}


--------------------Best params for RandomForest--------------------
{'n_estimators': 100, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': None}


--------------------Best params for XGBoost--------------------
{'n_estimators': 100, 'max_depth': 10, 'learning_rate': 0.1, 'colsample_bytree': 0.7}

In [53]:
# retraining models with best params
models= {
    'Adaboost': AdaBoostRegressor(n_estimators=100, loss='exponential', learning_rate=0.01),
    'RandomForest': RandomForestRegressor(n_estimators=100, min_samples_split=5, min_samples_leaf=1, max_features='sqrt', max_depth=None),
    'XGBoost': XGBRegressor(n_estimators=100, max_depth=10, learning_rate=0.1, colsample_bytree=0.7)
}

In [54]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train , y_train)
    
    y_train_pred= model.predict(x_train)
    y_test_pred= model.predict(x_test)
    
    #training set performance
    model_train_rsme=root_mean_squared_error(y_train , y_train_pred)
    model_train_mae= mean_absolute_error(y_train , y_train_pred )
    model_train_mse= mean_squared_error(y_train , y_train_pred)
    model_train_r2score= r2_score(y_train , y_train_pred)
    
    #test set performance
    model_test_rsme=root_mean_squared_error(y_test , y_test_pred)
    model_test_mae= mean_absolute_error(y_test , y_test_pred )
    model_test_mse= mean_squared_error(y_test , y_test_pred)
    model_test_r2score= r2_score(y_test , y_test_pred)
    
    print(list(models.keys())[i])
    
    print('Model performance for training set')
    print('- Mean squared error :{:.4f}'.format(model_train_mse))
    print('- Mean absolute error: {:.4f}'.format(model_train_mae))
    print('- Root mean squared error : {:.4f}'.format(model_train_rsme))
    print('- R2_score : {:.4f}'.format(model_train_r2score))
    
    print('='*35)
    
    print('Model performance for test set')
    print('- Mean squared error :{:.4f}'.format(model_train_mse))
    print('- Mean absolute error: {:.4f}'.format(model_train_mae))
    print('- Root mean squared error : {:.4f}'.format(model_train_rsme))
    print('- R2_score : {:.4f}'.format(model_train_r2score))
    
    print('='*35)
    print()

Adaboost
Model performance for training set
- Mean squared error :1790775505.7133
- Mean absolute error: 21375.0925
- Root mean squared error : 42317.5555
- R2_score : 0.6249
===================================
Model performance for test set
- Mean squared error :1790775505.7133
- Mean absolute error: 21375.0925
- Root mean squared error : 42317.5555
- R2_score : 0.6249
===================================

RandomForest
Model performance for training set
- Mean squared error :759334924.1691
- Mean absolute error: 8164.3799
- Root mean squared error : 27556.0324
- R2_score : 0.8409
===================================
Model performance for test set
- Mean squared error :759334924.1691
- Mean absolute error: 8164.3799
- Root mean squared error : 27556.0324
- R2_score : 0.8409
===================================

XGBoost
Model performance for training set
- Mean squared error :126833200.0000
- Mean absolute error: 8141.7803
- Root mean squared error : 11262.0244
- R2_score : 0.9734
===================================
Model performance for test set
- Mean squared error :126833200.0000
- Mean absolute error: 8141.7803
- Root mean squared error : 11262.0244
- R2_score : 0.9734
===================================